apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: fraud-detection/spark:latest
        ports:
        - containerPort: 7077
        - containerPort: 8080
        env:
        - name: SPARK_MODE
          value: "master"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  ports:
  - port: 7077
    targetPort: 7077
  selector:
    app: spark-master 